version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew build
